pool:
  name: Hosted VS2017
  demands: npm

steps:
  - task: Npm@1
    displayName: 'npm install'
    inputs:
      workingDir: src
      verbose: false

  - task: Npm@1
    displayName: 'npm custom'
    inputs:
      command: custom
      workingDir: src
      verbose: false
      customCommand: 'run build'

  - task: DotNetCoreCLI@2
    displayName: 'dotnet build'
    inputs:
      arguments: '-c Release'

  - task: DotNetCoreCLI@2
    displayName: 'dotnet test'
    inputs:
      command: test
      projects: 'tests/**/*.csproj'

  - task: PowerShell@2
    displayName: 'PowerShell Script'
    inputs:
      targetType: filePath
      filePath: './src/nuget-push.ps1'
      workingDirectory: src
    env:
      nugetApiKey: oy2lekrra62eooalkoaaqoctldwo2b4uxff7nek25vozza
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
