pool:
  vmImage: ubuntu-16.04

steps:
  - task: Npm@1
    displayName: 'npm install'
    inputs:
      workingDir: src
      verbose: false

  - task: Npm@1
    displayName: 'npm build'
    inputs:
      command: custom
      workingDir: src
      verbose: false
      customCommand: 'run build'

  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '2.2.401'

  - task: DotNetCoreCLI@2
    displayName: 'dotnet build'
    inputs:
      arguments: '-c Release'

  - task: DotNetCoreCLI@2
    displayName: 'dotnet test'
    inputs:
      command: test
      projects: 'tests/**/*.csproj'
