pool:
  vmImage: ubuntu-16.04

variables:
  buildConfiguration: Release

steps:
  - task: Npm@1
    displayName: 'npm install'
    inputs:
      workingDir: src
      verbose: false

  - task: Npm@1
    displayName: 'npm build'
    inputs:
      command: custom
      workingDir: src
      verbose: false
      customCommand: 'run build'

  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '2.2.401'

  - task: DotNetCoreCLI@2
    displayName: 'Restore'
    inputs:
      command: restore

  - task: DotNetCoreCLI@2
    displayName: 'Build'
    inputs:
      command: build
      arguments: '-c $(buildConfiguration)'

  - task: DotNetCoreCLI@2
    displayName: 'Test'
    inputs:
      command: test
      projects: 'tests/**/*.csproj'

  - task: DotNetCoreCLI@2
    displayName: 'Pack'
    condition: and(succeeded(), or(eq(variables['Build.SourceBranchName'], 'master'),eq(variables['Build.SourceBranchName'], 'develop')))
    inputs:
      command: pack
      arguments: '-c $(buildConfiguration) --no-build -o %Build_ArtifactStagingDirectory%'

  - task: PublishBuildArtifacts@1
    inputs:
      artifactName: 'package'